### ISSUE TITLE
Cannot compile ISO on latest QEMU

### ISSUE THREAD

**Issue by JasonBreen** [Zeal-Operating-System/ZealOS#142]
Im trying to run build-iso.sh, but keep getting these errors, along with no ISOs built.
![Screenshot from 2023-12-05 18-49-04](https://github.com/Zeal-Operating-System/ZealOS/assets/3111341/de7d30c1-a39c-4647-8e34-40836709ada1)
![Screenshot from 2023-12-05 18-52-55](https://github.com/Zeal-Operating-System/ZealOS/assets/3111341/b6302b98-4324-40bc-9c90-3c65ea6f178c)

**Comment by doodayev** [comment]
This is a duplicate issue of issue #139
https://github.com/Zeal-Operating-System/ZealOS/issues/139

**Comment by GutPuncher** [comment]
Thanks @doodayev , closed as duplicate. Please track on #139
