### ISSUE TITLE
Thanks for making that and posting it! Recommend opening a "Discussions" on the repo for more community style interaction to encourage more people to get involved. 

### ISSUE THREAD

**Issue by 01GOD** [Zeal-Operating-System/ZealOS#158]
Hi, 

Sadly the main "ritual" in the first and second "TEMPLES" was animal sacrifice, and I hate that and MY AVATAR maintains vegetarian dietary habits. If a third such building was built for murdering animals as a profiteering scam again in @ssrael, I would HAPPILY DESTROY IT AGAIN. So I will consider TempleOS to be THE FIRST of the operating system TEMPLES and not based on any historical henotheistic/polytheistic messes named (somewhat aptly, sadly) after a HORRIBLE lying scumbag that sold his own brother. 

That said, I recently interviewed for an engineering position at Apple and today saw what the Darwin OS mascot sadly is. Thus, any good open source OS that doesn't have ANY such demented bsd crap in it is nice to have in the World. Any that know what the original pricing of the apple 1 computer was can look at that OS mascot and get very concerned quickly, especially considering that the "apple vision pro" is basically a mobile "matrix" that could be used to hide TRUTH from the humans. A past interviewer in an Apple engineering interview I did said the "d" word the WRONG way (it's SUPPOSED to be pronounced DAYmon) so casually that the interview was basically over, as I didn't want to be on a team making ANY such horrible things !!! 

I thankfully designed and prototyped a fully fully functional 1080P HMD product before Oculus shipped the first Oculus HMD that had that resolution, and I recently thankfully launched a new mini computer product.  There thankfully is Linux and Android, but it is certainly nice to have another good alternative. 

So thanks to any of the human dream characters that have been making TempleOS better and are making newer, better editions of that OS and GOOD OS's that don't have ANY dark bsd sort of mascots! 

PS: An edition of Darwin OS with a NOBLE ANGEL OF LIGHT standing on a slain bsd mascot with a spear in it could be an interesting thing to make though, if any reading this would like to. I would maybe make that someday, but I have been studying and practicing A LOT to get a great salaried software engineering position at a tech company, so that I won't ponder auto-euthanasia anymore.

**Comment by GutPuncher** [comment]
Community interaction with Zeal takes place in the ZealOS Discord Server https://discord.gg/rK6U3xdr7D
