### ISSUE TITLE
Add mouse aim to CastleFrankenstein.

### ISSUE THREAD

**Issue by TomAwezome** [Zeal-Operating-System/ZealOS#44]

**Comment by xslendix** [comment]
Mouse aim doesn't imply adding the Y axis, you can just implement the X axis and only have that. Of course, aiming would feel weird, so you can implement it DOOM style where you can move the camera along the Y axis but ignore it in the game logic.

**Comment by y4my4my4m** [comment]
@xslendix Ok, thank you!

I'll see if I can do it. Also, DOOM style would imply *no* Y axis 😉
