### ISSUE TITLE
Does this have any CIA backdoors?

### ISSUE THREAD

**Issue by AVeryNormalGuy** [Zeal-Operating-System/ZealOS#61]
This operating system slightly glows for me. Does this have any CIA backdoors?

**Comment by TomAwezome** [comment]
If you find any bugs, typos, missing documentation, backdoors, or have any improvements or contributions to the project, you are free to submit a PR

**Comment by y4my4my4m** [comment]
> This operating system slightly glows for me. Does this have any CIA backdoors?

It's open source, just look.
Oh you don't understand anything about this code? 

Then what would it matter what we respond to this issue. We could say whatever and you wouldn't know.

So, I guess it only leaves you with one option: read the code.

**Comment by MacSlash** [comment]
top ten dumbest issues to ever
