### ISSUE TITLE
Modify Bootloader

### ISSUE THREAD

**Issue by emir4169** [Zeal-Operating-System/ZealOS#72]
I would like a complete remake of the bootloader. with it being able to detect if a disk belongs to a cd or if it doesnt.
and fix a problem i had with vanilla templeOS that it just wouldnt want to boot my linux mint iso (cause it was in a vm)

**Comment by TomAwezome** [comment]
@emir4169 Once you have implemented it or modified the existing bootloader to have these features, please make a PR and link it to this Issue.

Thanks and have a great day

**Comment by TomAwezome** [comment]
If you need any help when you are creating this, just let me know what specific areas you need advice with

**Comment by TomAwezome** [comment]
If no PR is submitted within 30 days adding your new functionality, this Issue will be marked closed and resolved

**Comment by emir4169** [comment]
(me with no c programming experience)

**Comment by TomAwezome** [comment]
That's okay, you can learn while using the OS, and make a PR and set it to Draft so you can learn while you build it

**Comment by xslendix** [comment]
Closing issue, gone stale.
