### ISSUE TITLE
Please reconsider your addition of further confusion to the fonts and encoding situation on TempleOS

### ISSUE THREAD

**Issue by ctrlcctrlv** [Zeal-Operating-System/ZealOS#73]
Cf. https://github.com/rendello/templeos_font/issues/4

I don't care if you want to use a more modern _style_, but changing the codepoint _identities_ is seriously annoying.

**Comment by ctrlcctrlv** [comment]
The problematic commit is 1745c7c4043207e07a099a8232e7759d1935fbe9 by @xmm15

**Comment by ctrlcctrlv** [comment]
The good news is it's not hard to restore the old font and rebuild the ISO.

![image](https://user-images.githubusercontent.com/838783/201539072-138f1e79-4f66-4f7d-b251-2a3e332ca1ed.png)

I assume you won't accept a reversion that doesn't also maintain the new style, @TomAwezome?

I note also the replacement of an operator with an arrow. That should've gone in one of the blank spaces.

**Comment by TomAwezome** [comment]
Hi, did you try `Ctrl-Alt-F` to toggle between thin font and thick font? The thin font is custom made my me, the thick font is ported from https://www.fontspace.com/public-pixel-font-f72305 .

If you would like to make a change, please submit a PR. Thank you and have a great day

**Comment by ctrlcctrlv** [comment]
@TomAwezome This isn't a problem of my personal system but an encoding issue. Software won't be compatible if you change character identities like this.

**Comment by TomAwezome** [comment]
I'm not sure I understand what you mean, Zeal is compatible with IBM CP437 and all modern software provides the ability to decode byte strings in that format

**Comment by TomAwezome** [comment]
The only character bitmap changed distinctly is the Reverse Not Sign character, replacing it with a left-facing arrow, to use with CallerRep, of which I searched deep and found that the symbol does not ever get used in mathematics, nor any kind of proper formal usage. It was, as far as I could tell, the only available character in the VGA ROM font character map that has fallen out of use completely.

**Comment by ctrlcctrlv** [comment]
Yes, but, Terry's encoding is not actually IBM Code Page 437. That becomes clear when I open it and force the encoding to be IBM437.

![image](https://user-images.githubusercontent.com/838783/201543651-360da8cc-9c74-44a8-9ae2-6c75da95e593.png)

**Comment by ctrlcctrlv** [comment]
There are plenty of open spaces and also you'll note duplications of characters found later between 0x02 and 0x0D. Terry also uses 0x1F as a "shift-space" as he called it, essentially it is a character that in TempleOS can co-exist with normal space (0x20) so that his automatic code formatting allowed him to mix tabs and spaces. I forget what video he explains it in. In a DolDoc, the shift-space is shown in grey.

**Comment by TomAwezome** [comment]
Sounds good. Once you've changed things to use the character positions that make more sense, make a PR please. Thank you

**Comment by ctrlcctrlv** [comment]
OK

**Comment by TomAwezome** [comment]
Once a PR is submitted, the changes can be reviewed and tested against the existing fonts and external build scripts

**Comment by TomAwezome** [comment]
I am also very early in development of a ZealC compiler/assembler/interpreter toolchain and will similarly test the changes against the prototype code on that to ensure it works the same before and after

**Comment by ctrlcctrlv** [comment]
Hey that's great, I had been thinking of working on that for a while. I really could ues a working Linux version of ToHTML.HC.Z lol.

**Comment by TomAwezome** [comment]
For the record, please keep this in mind: the "shift-space" functionality you [mentioned](https://github.com/Zeal-Operating-System/ZealOS/issues/73#issuecomment-1312817270) was removed from ZealOS long ago, and is deprecated and no longer present in Zeal. So that character is no longer valid in Zeal's fontset.  Also of note, the box-drawing characters Zeal uses are the IBM CP437 box drawing characters. 

Zeal does not use characters \0000 through \001F, at all.

**Comment by TomAwezome** [comment]
The only usage I know of a character in the \0000-\0020 range that Zeal uses is the same character that stock TOS uses, the 0x5 character to track DolDoc cursor which the DolDoc code automatically embeds into code files when using the OS. In that situation, `CursorRemove("/*");` can be run to clean those out of files before syncing VM files to repository.
