### ISSUE TITLE
Not like TempleOS

### ISSUE THREAD

**Issue by grepwood** [Zeal-Operating-System/ZealOS#74]
I don't necessarily oppose or favor the changes that make ZealOS break TempleOS' design guidelines. This thread should only serve to document just how different ZealOS is from TempleOS, by pointing out where and how it has strayed away from how Terry envisioned the system and how he said it should be.

We should try to quote Terry to back up any instance of non-compliance, and of course keep it civil.

**Comment by TomAwezome** [comment]
https://zeal-operating-system.github.io/Doc/ChangeLog.DD.html

**Comment by TomAwezome** [comment]
ZealOS is a complete fork from the stock OS and allows for complete user control and experimentation. Almost any PR that produces functional behaviour is merged quickly.

**Comment by grepwood** [comment]
Graphics

Terry explains that 640x480 in 16 colors is the founding principle. If I understand his elephant example correctly, his argument boils down to the following:
> pretty much everyone can draw a reasonably okay looking elephant within 640x480x4 even if it looks like toddler doodles
> if you give yourself more space and colors, you're kinda expected by your audience to produce a better looking elephant
> you can't expect everyone to be able to do this
Sources:
[0] - https://www.youtube.com/watch?v=4dQumAULdCE - Terry Davis - "The Founding Principle Is 640x480"

**Comment by TomAwezome** [comment]
Terry used 800x600 in LoseThos, which is what ZealOS is inspired moreso by.

**Comment by TomAwezome** [comment]
https://web.archive.org/web/20060702135534/http://www.losethos.com/
![image](https://user-images.githubusercontent.com/10574504/201548276-48b77cda-947b-4579-a606-2c50c931e8fc.png)

**Comment by TomAwezome** [comment]
https://github.com/Zeal-Operating-System/ZealOS/blob/master/src/System/Utils/ConversionScript.ZC
