### ISSUE TITLE
Build system uses a dangerous mount point for temporary disk image

### ISSUE THREAD

**Issue by alula** [Zeal-Operating-System/ZealOS#9]
https://github.com/Zeal-Operating-System/ZealOS/blob/8306996ff4a370db927f222e88db5b89c7285a59/build/build_iso.sh

The build system for some reason uses `/mnt` as a mount point for the disk image and completely erases it's contents (`rm -rf`) on each invocation. This can lead to a pretty negative surprise if the user had an external drive mounted there.

A much better and way safer option would be eg. using a randomly named and newly created directory located in `/tmp`.

**Comment by y4my4my4m** [comment]
Would be more sensical to use `/mnt/zealos_tmp` than `/tmp`

**Comment by alula** [comment]
`/tmp/something` is fine as well since it's only there for build time.

**Comment by y4my4my4m** [comment]
@alula fair enough, don't forget it's also used

in these two scripts:
https://github.com/Zeal-Operating-System/ZealOS/blob/master/build/sync_repo.sh
https://github.com/Zeal-Operating-System/ZealOS/blob/master/build/sync_vm.sh

**Comment by Ccode-lang** [comment]
I'll work on this!

**Comment by Ccode-lang** [comment]
Done!
