### ISSUE TITLE
How do I change the resolution?

### ISSUE THREAD

**Issue by billyblackburn** [Zeal-Operating-System/ZealOS#92]
Im kinda new to this.  I get the VideoRep; to open but how do I change it?

**Comment by xslendix** [comment]
If you are using Limine, you need to go into ::/Boot/Limine.CFG and change the resolution there. If you are using the traditional BIOS option, you need to re-compile the kernel.

**Comment by TomAwezome** [comment]
Additionally, if using the traditional Public Domain BIOS installation, you will need to edit /Kernel/KStart16.ZC and change the values in `REQUESTED_SCREEN_WIDTH` and `REQUESTED_SCREEN_HEIGHT`. Then you can recompile the kernel with `BootHDIns;` [following the instructions on the wiki.](https://github.com/Zeal-Operating-System/ZealOS/wiki/Kernel-Recompiling)

**Comment by billyblackburn** [comment]
> Additionally, if using the traditional Public Domain BIOS installation, you will need to edit /Kernel/KStart16.ZC and change the values in `REQUESTED_SCREEN_WIDTH` and `REQUESTED_SCREEN_HEIGHT`. Then you can recompile the kernel with `BootHDIns;` [following the instructions on the wiki.](https://github.com/Zeal-Operating-System/ZealOS/wiki/Kernel-Recompiling)

this will be my route.....thank you

**Comment by TomAwezome** [comment]
I have created a new Wiki page, based on the discussion on this Issue. https://github.com/Zeal-Operating-System/ZealOS/wiki/Changing-Screen-Resolution
